version: "3.8"

services:
 minecraft-server:
   container_name: minecraft-server
   image: itzg/minecraft-server
   ports:
     - "25565:25565"
   environment:
     EULA: "TRUE"
     TYPE: MOHIST
     MEMORY: 8G
     VERSION: 1.18.2
     DEBUG: "true"
   volumes:
     - ./data:/data